name: Deploy QA Sanity
on: workflow_dispatch
defaults:
 run:
  working-directory: ./studio
jobs:
  sanity-deploy:
    runs-on: ubuntu-18.04
    name: Deploy Sanity dataset
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
            node-version: 12.x
      - name: Install dependencies
        run: |
            npm install
      - name: Deploy Sanity
        run: |
            set -e
            
            sanity install && SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" sanity deploy