name: Deploy Production Sanity
on: push

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  SANITY_STUDIO_API_DATASET: production

defaults:
 run:
  working-directory: ./studio
jobs:
  deploy:
    name: Deploy Sanity UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
  sanity-deploy:
    runs-on: ubuntu-18.04
    name: Deploy Sanity dataset
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
            node-version: 12.x
      - name: Install dependencies
        run: |
            npm install
      - name: Deploy Sanity
        run: |
            set -e
            
            sanity install && SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" sanity deploy