name: Deploy Production Sanity
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy Sanity UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jossef/action-set-json-field@v2
        with:
           file: ./studio/config/plausible-iframe.json
           field: site
           value: ${{ secrets.PLAUSIBLE_AUTH_TOKEN}}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./studio --remote-only